adadaval=input("adadaval:")
adaddovom=input("adaddovom")
jam=int(adadaval)+int(adaddovom)
#print("jam: ",jam)
zarb=int(adadaval)*int(adaddovom)
#print("zarb :",zarb)
tafriq=int(adadaval)-int(adaddovom)
#print("tafriq",tafriq)
taqsim=int(adadaval)/int(adaddovom)
#print("taqsim",taqsim)
print(" jam : " , jam ,"\t","zarb : ",zarb , "\ttafriq : ", tafriq , "\ttaqsim : " , taqsim)
